//
//  ListOffersInteractor.swift
//  FyberClient
//
//  Created by Mohammed Safwat on 1/28/17.
//  Copyright (c) 2017 Mohammed Safwat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ListOffersInteractorInput {
    func fetchOffers(request: ListOffers.FetchOffers.Request)
    var offers: [Offer]? { get }
}

protocol ListOffersInteractorOutput {
    func presentFetchedOffers(response: ListOffers.FetchOffers.Response, error: OffersStoreError?)
}

class ListOffersInteractor: ListOffersInteractorInput {
    var output: ListOffersInteractorOutput!
    var offersWorker = ListOffersWorker(offersStore: OffersAPIManager())
    
    var offers: [Offer]?

    // MARK: - Business logic
    func fetchOffers(request: ListOffers.FetchOffers.Request) {
        offersWorker.fetchOffers(userId: request.userId, appId: request.appId, securityToken: request.securityToken) { (offers: [Offer], error: OffersStoreError?)
            in
            self.offers = offers
            let response = ListOffers.FetchOffers.Response(offers: offers, error: error)
            self.output.presentFetchedOffers(response: response, error: error)
        }
    }
}
