//
//  ListOffersConfigurator.swift
//  FyberClient
//
//  Created by Mohammed Safwat on 1/28/17.
//  Copyright (c) 2017 Mohammed Safwat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ListOffersViewController: ListOffersPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension ListOffersInteractor: ListOffersViewControllerOutput {
    
}

extension ListOffersPresenter: ListOffersInteractorOutput {
    
}

class ListOffersConfigurator {
    // MARK: - Object lifecycle
    
    static let sharedInstance = ListOffersConfigurator()
    
    private init() {}

    // MARK: - Configuration

    func configure(viewController: ListOffersViewController) {
        let router = ListOffersRouter()
        router.viewController = viewController

        let presenter = ListOffersPresenter()
        presenter.output = viewController

        let interactor = ListOffersInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
    
    func registerTableViewCell(tableView: UITableView, cellName: String?) {
        if let cellName = cellName {
            tableView.register(UINib(nibName: cellName, bundle: Bundle.main), forCellReuseIdentifier: cellName)
        }
    }
    
    func configureTableViewSeparatorStyle(tableView: UITableView, tableViewSeparatorStyle: UITableViewCellSeparatorStyle) {
        tableView.separatorStyle = tableViewSeparatorStyle
    }
    
    func configureTableViewBackgroundColor(tableView: UITableView, backgroundColor: UIColor?) {
        tableView.backgroundColor = backgroundColor
    }
}
