//
//  ListOffersModels.swift
//  FyberClient
//
//  Created by Mohammed Safwat on 1/28/17.
//  Copyright (c) 2017 Mohammed Safwat. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ListOffers {
    struct FetchOffers {
        struct Request {
            var appId: String?
            var userId: String?
            var securityToken: String?
        }

        struct Response {
            var offers: [Offer]
            var error: OffersStoreError?
        }

        struct ViewModel {
            struct DisplayedOffer {
                var offerTitle: String?
                var offerID: Int
                var offerTeaser: String?
                var offerAction: String?
                var offerLowResolutionThumbnailURL: String?
                var offerHighResolutionThmbnailURL: String?
                var offerPayoutAmount: Int
            }
            struct DisplayedError {
                var errorTitle: String?
                var errorMessage: String?
            }
            var displayedOffers: [DisplayedOffer]
            var displayedError: DisplayedError?
        }
    }
}
